Hw 04 lection 2 3
js-tasks-ru/htmlcss-20220120_olegkhacv pull request #6
Opened 2022-02-04 14:44 UTC by OlegKha

Main layout

2022-02-04 17:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-04 19:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-05 07:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-05 19:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-05 20:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-06 19:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-07 21:50 UTC, GSemikozov requested changes

2022-02-07 21:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 20px;
точно ли по дизайну?)

2022-02-07 21:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    background: #FFFFFF;
все цвета проставим из переменных

2022-02-07 21:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    position: absolute;
не стоит через absolute, пусть идет в общем потоке

2022-02-07 21:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
поскольку это дочерний элемент флекс-контейнера, можем вместо width использовать flex-basis: 9px

2022-02-07 21:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
высоту проставим инлайном, в процентах, никаких значений по умолчанию здесь не нужно (если с сервера не придет значение а мы покажем 100% - то обманем пользователя)

2022-02-07 21:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-items: flex-end;
не хватает фиксированной высоты относительно которой будем задавать высоту дочерним элементам в процентах

2022-02-07 21:50 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__item_small{
и тогда эти модификаторы будут не нужны

2022-02-08 21:28 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +    padding: 20px;
подкоректировал отступы, шрифт.
дело в этом?

2022-02-08 21:28 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +    background: #FFFFFF;
done

2022-02-08 21:30 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
done

2022-02-08 21:34 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
done

2022-02-08 21:38 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +    align-items: flex-end;
done

2022-02-08 21:44 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +.histogram__item_small{
убрал модификаторы

2022-02-08 21:58 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +    position: absolute;
изначально так и было, просто двигал флексом, но как тогда быть со ссылкой?
её область = высоте блока.

2022-02-08 22:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-08 22:04 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 20px;
на самом деле отступы по макету такие - padding: 16px 24px 24px;

2022-02-08 22:05 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    position: absolute;
не совсем понимаю как высота ссылки может = высоте блока. Предлагаю сделать скриншот выделенной области относительно того, что имеется в виду. Или любой другой удобный вариант)

2022-02-08 22:06 UTC, GSemikozov requested changes

2022-02-08 22:06 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 100%;
до сих пор висит

2022-02-08 22:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-08 22:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-08 22:26 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +    padding: 20px;
done

2022-02-08 22:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-08 22:37 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +    position: absolute;
![Screenshot 2022-02-09 003714](https://user-images.githubusercontent.com/62078876/153087409-ffe964a4-cb68-4c32-8a93-3334dcbb9b46.png)

2022-02-08 22:43 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +    height: 100%;
если убрать height: 100% получаем:
![image](https://user-images.githubusercontent.com/62078876/153087983-4cef18e1-cfa5-4170-9593-c06a7bba805c.png)

2022-02-08 22:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-09 09:23 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    position: absolute;
в зависимости от реализации либо flex-shrink либо flex-grow запретить

2022-02-09 19:32 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +    position: absolute;
пробую и шринк и гров - никаких изменений
![shrinkorgrow](https://user-images.githubusercontent.com/62078876/153276222-28e2b6e3-1a02-4abd-915a-9777680997b8.png)
л

2022-02-09 20:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-09 21:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-09 21:24 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +    height: 100%;
в чем был мой тупеж понял. готово.

2022-02-09 21:27 UTC, OlegKha commented on 04-lection2/01-histogram/histogram.css
> +    position: absolute;
разобрался.
использовал align-self: baseline;

2022-02-09 21:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-10 15:17 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    position: absolute;
отлично

2022-02-10 15:18 UTC, GSemikozov approved these changes

2022-02-10 15:18 UTC, merged